#!/bin/bash

SCRIPT_HOME=$(cd $(dirname $0);pwd)
source $SCRIPT_HOME/modules

SEND_FILE=${1:-""}
NETNS_ID=${2:-""}
key_name=${3:-""}
ssh_user=${4:-""}
MANAGER_IP=${5:-""}
OUTPUT_NAME=${6:-""}

VERIFY_DIR="/usr/lib/verification"

function show_options () {
    echo "Options:"
    echo "bootstrap_extend <send file path> <netns> <key_name> <ssh_user> <manager_ip> <output_name>"
    exit 1
}

function check_input() {
  if [ -z "$SEND_FILE" -o -z "$NETNS_ID" -o -z "$key_name" -o -z "$ssh_user" -o -z "$MANAGER_IP" ]; then
    show_options
  fi
  if [ ! -e "$SEND_FILE" ]; then
    echo "No such file."
    show_options
  fi
}

function exec_scp() {
   while :
   do
      sudo ip netns exec ${NETNS_ID} scp -oStrictHostKeyChecking=no -i "${SCRIPT_HOME}/../keys/${key_name}.pem" ${1} ${ssh_user}@${2}:${3} >/dev/null 2>&1
      if [ $? -eq "0" ]; then
         echo "   : )"
         break
      fi
      sleep 2 
   done
}

function send_file() {
   echo "Transfer of ${OUTPUT_NAME} information to Manager.."
   exec_scp ${SEND_FILE} ${MANAGER_IP} "${VERIFY_DIR}/${OUTPUT_NAME}"
}

check_input

send_file &
progress

sleep 1

if [ -e ${SEND_FILE} ]; then
   rm -r ${SEND_FILE}
fi

exit 0
